name: Build OpenClash IPK (23.05.5 x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget curl ccache

      - name: Download SDK
        run: |
          set -e
          URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          curl -fL -o sdk.tar.xz "$URL" || curl -fL -o sdk.tar.xz "https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          tar -xJf sdk.tar.xz
          echo "SDK_DIR=$(ls -d openwrt-sdk-23.05.5-x86-64_* | head -n1)" >> $GITHUB_ENV

      - name: Prepare feeds
        run: |
          set -e
          cd "$SDK_DIR"
          # 写入 feeds（逐行，避免 heredoc）
          printf "%s\n" \
          "src-git packages  https://git.openwrt.org/feed/packages.git;openwrt-23.05" \
          "src-git luci      https://git.openwrt.org/project/luci.git;openwrt-23.05" \
          "src-git routing   https://git.openwrt.org/feed/routing.git;openwrt-23.05" \
          "src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-23.05" \
          "src-git openclash https://github.com/vernesong/OpenClash" \
          > feeds.conf.default
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -p packages bash curl ca-bundle unzip ruby ruby-yaml || true
          ./scripts/feeds install -p openclash luci-app-openclash

      - name: Build OpenClash
        run: |
          set -e
          cd "$SDK_DIR"
          rm -f .config .config.old
          make defconfig
          make package/feeds/openclash/luci-app-openclash/{download,compile} -j$(nproc) V=s || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openclash-ipk
          path: ${{ env.SDK_DIR }}/bin/packages
