name: Build luci-app-ssr-plus (23.05.5 x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DL_DIR: ${{ github.workspace }}/dl
      CCACHE_DIR: ${{ github.workspace }}/ccache
      JOBS: 8
    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Ubuntu 24.04)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev file \
            wget curl ccache python3 python3-pip python3-venv python3-setuptools
          python3 -m pip install --upgrade pip setuptools wheel

      - name: Prepare cache dirs
        run: mkdir -p "${DL_DIR}" "${CCACHE_DIR}"

      - name: Cache downloads
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_DIR }}
          key: dl-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            dl-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            ccache-

      - name: Download SDK (with mirror fallback)
        shell: bash
        run: |
          set -e
          URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          TUNA="${URL/https:\/\/downloads.openwrt.org/https:\/\/mirrors.tuna.tsinghua.edu.cn/openwrt}"
          SAU="${URL/https:\/\/downloads.openwrt.org/https:\/\/mirrors4.sau.edu.cn/openwrt}"
          for U in "$URL" "$TUNA" "$SAU"; do
            echo "try $U"
            curl -fL --retry 4 -C - -o sdk.tar.xz "$U" && break
          done
          tar -xJf sdk.tar.xz
          SDK_DIR="$(ls -d openwrt-sdk-23.05.5-x86-64_* | head -n1)"
          echo "SDK_DIR=$SDK_DIR" >> "$GITHUB_ENV"

      - name: Prepare feeds (official + helloworld only)
        shell: bash
        run: |
          set -e
          cd "$SDK_DIR"
          {
            echo 'src-git packages  https://git.openwrt.org/feed/packages.git;openwrt-23.05'
            echo 'src-git luci      https://git.openwrt.org/project/luci.git;openwrt-23.05'
            echo 'src-git routing   https://git.openwrt.org/feed/routing.git;openwrt-23.05'
            echo 'src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-23.05'
            echo 'src-git helloworld https://github.com/fw876/helloworld'
          } > feeds.conf.default

          ./scripts/feeds clean
          ./scripts/feeds update -a

          # 安装 SSR Plus 到源码树
          ./scripts/feeds install -p helloworld luci-app-ssr-plus

      - name: Build SSR Plus (plugins only)
        shell: bash
        run: |
          set -e
          cd "$SDK_DIR"
          rm -f .config .config.old
          make defconfig

          # 先编 LuCI host 工具（提供 po2lmo）
          make package/feeds/luci/luci-base/host/compile V=s

          # 只编 SSR Plus
          make package/feeds/helloworld/luci-app-ssr-plus/{download,compile} -j"${JOBS}" V=s

      - name: Collect outputs
        shell: bash
        run: |
          set -e
          cd "$SDK_DIR"
          mkdir -p _out
          find bin/packages -type f -name "*.ipk" -exec cp -v {} _out/ \; || true
          echo "OUT_DIR=$(pwd)/_out" >> "$GITHUB_ENV"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssrplus-ipks-23.05.5-x86_64
          path: ${{ env.OUT_DIR }}
