name: Build OpenWrt IPKs (23.05.5 x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget curl ccache

      - name: Download SDK
        run: |
          set -eux
          URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          # 有些地区下载慢，自动回退清华镜像
          curl -fL -o sdk.tar.xz "$URL" || \
          curl -fL -o sdk.tar.xz "https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.5/targets/x86/64/$(basename "$URL")"
          tar -xJf sdk.tar.xz
          echo "SDK_DIR=$(ls -d openwrt-sdk-23.05.5-x86-64_* | head -n1)" >> $GITHUB_ENV

      - name: Prepare feeds
        run: |
          set -eux
          cd "$SDK_DIR"
          cat > feeds.conf.default <<'EOF'
          src-git packages  https://git.openwrt.org/feed/packages.git;openwrt-23.05
          src-git luci      https://git.openwrt.org/project/luci.git;openwrt-23.05
          src-git routing   https://git.openwrt.org/feed/routing.git;openwrt-23.05
          src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-23.05
          # 独立三方源（拆开避免冲突）
          src-git openclash  https://github.com/vernesong/OpenClash
          src-git helloworld https://github.com/fw876/helloworld
          src-git turboacc   https://github.com/chenmozhijin/turboacc.git
          EOF
          ./scripts/feeds clean
          ./scripts/feeds update -a
          # 把常见依赖放进源码树（只是让编译器能解析依赖）
          ./scripts/feeds install -p packages bash curl ca-bundle unzip ruby ruby-yaml || true
          ./scripts/feeds install -p openclash  luci-app-openclash || true
          ./scripts/feeds install -p helloworld luci-app-ssr-plus  || true
          ./scripts/feeds install -p turboacc  luci-app-turboacc  || true

      - name: Build IPKs
        run: |
          set -eux
          cd "$SDK_DIR"
          rm -f .config .config.old
          make defconfig
          # 只编目标包及其依赖（不会编世界）
          make package/feeds/openclash/luci-app-openclash/{download,compile} -j"$(nproc)" V=s || true
          make package/feeds/helloworld/luci-app-ssr-plus/{download,compile}  -j"$(nproc)" V=s || true
          make package/feeds/turboacc/luci-app-turboacc/{download,compile}   -j"$(nproc)" V=s || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipks-23.05.5-x86_64
          path: ${{ env.SDK_DIR }}/bin/packages
