name: Build OpenWrt 23.05.5 x86_64 with SSR-Plus
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev python3 \
            unzip zlib1g-dev file wget rsync libelf-dev ccache tar xz-utils jq

      - name: Download SDK & ImageBuilder (23.05.5)
        run: |
          set -e
          BASE_URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/"
          SDK_TAR="openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          IB_TAR="openwrt-imagebuilder-23.05.5-x86-64.Linux-x86_64.tar.xz"

          wget -q "${BASE_URL}${SDK_TAR}" -O "${SDK_TAR}"
          wget -q "${BASE_URL}${IB_TAR}"  -O "${IB_TAR}"
          tar -xf "${SDK_TAR}"
          tar -xf "${IB_TAR}"

          echo "SDK_DIR=$(find . -maxdepth 1 -type d -name 'openwrt-sdk-*' | head -n1)" >> $GITHUB_ENV
          echo "IB_DIR=$(find . -maxdepth 1 -type d -name 'openwrt-imagebuilder-*' | head -n1)" >> $GITHUB_ENV

      - name: Build luci-app-ssr-plus with SDK (via feeds)
        run: |
          set -e
          cd "$SDK_DIR"

          echo 'src-git helloworld https://github.com/fw876/helloworld' >> feeds.conf.default
          echo 'src-git small https://github.com/kenzok8/small-package' >> feeds.conf.default

          ./scripts/feeds update -a
          ./scripts/feeds install -p luci luci-compat || true
          ./scripts/feeds install -p helloworld luci-app-ssr-plus
          ./scripts/feeds install -p helloworld shadowsocksr-libev-ssr-local shadowsocksr-libev-ssr-redir
          ./scripts/feeds install -p small dns2socks microsocks ipt2socks pdnsd-alt redsocks2

          cat > .config <<'EOF'
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_pdnsd-alt=y
          CONFIG_PACKAGE_redsocks2=y
          EOF

          make defconfig
          make package/luci-app-ssr-plus/compile -j"$(nproc)" V=s || true
          make package/shadowsocksr-libev/compile -j"$(nproc)" V=s || true
          make package/dns2socks/compile       -j"$(nproc)" V=s || true
          make package/microsocks/compile      -j"$(nproc)" V=s || true
          make package/ipt2socks/compile       -j"$(nproc)" V=s || true
          make package/pdnsd-alt/compile       -j"$(nproc)" V=s || true
          make package/redsocks2/compile       -j"$(nproc)" V=s || true

          mkdir -p "../$IB_DIR/packages"
          find bin/ -type f -name '*.ipk' -exec cp -av {} "../$IB_DIR/packages/" \;

      - name: Build firmware with ImageBuilder
        run: |
          set -e
          cd "$IB_DIR"
          PKG_LIST="luci luci-compat luci-app-ssr-plus \
                    shadowsocksr-libev-ssr-local shadowsocksr-libev-ssr-redir \
                    dns2socks microsocks ipt2socks pdnsd-alt redsocks2"
          make info
          make image PROFILE=generic PACKAGES="$PKG_LIST"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-23.05.5-x86_64-ssrplus
          path: ${{ env.IB_DIR }}/bin/targets/x86/64/*
