name: Build OpenWrt 23.05.5 x86_64 with SSR-Plus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev python3 \
            unzip zlib1g-dev file wget rsync libelf-dev ccache tar xz-utils jq

      - name: Download SDK & IB (23.05.5 x86_64)
        run: |
          BASE_URL="https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/"
          SDK=$(curl -s $BASE_URL | grep -oE "openwrt-sdk-23.05.5-x86-64.*tar.xz" | head -n1)
          IB=$(curl -s $BASE_URL | grep -oE "openwrt-imagebuilder-23.05.5-x86-64.*tar.xz" | head -n1)
          wget $BASE_URL$SDK
          wget $BASE_URL$IB
          tar -xf $SDK
          tar -xf $IB
          echo "SDK_DIR=$(find . -maxdepth 1 -type d -name 'openwrt-sdk-*')" >> $GITHUB_ENV
          echo "IB_DIR=$(find . -maxdepth 1 -type d -name 'openwrt-imagebuilder-*')" >> $GITHUB_ENV

      - name: Build luci-app-ssr-plus with SDK
        run: |
          cd $SDK_DIR
          mkdir -p package/custom
          git clone --depth=1 https://github.com/fw876/helloworld.git package/custom/helloworld
          git clone --depth=1 https://github.com/kenzok8/small-package.git package/custom/small
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cat > .config <<EOF
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_pdnsd-alt=y
          CONFIG_PACKAGE_redsocks2=y
          EOF
          make defconfig
          make package/luci-app-ssr-plus/compile -j$(nproc) V=s || true
          find bin/ -name "*.ipk" -exec cp {} ../$IB_DIR/packages/ \;

      - name: Build final firmware with ImageBuilder
        run: |
          cd $IB_DIR
          make image PROFILE=generic \
            PACKAGES="luci luci-compat luci-app-ssr-plus \
                      shadowsocksr-libev-ssr-local shadowsocksr-libev-ssr-redir \
                      dns2socks microsocks ipt2socks pdnsd-alt redsocks2"

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt-23.05-x86_64-ssrplus
          path: ${{ env.IB_DIR }}/bin/targets/x86/64/*
