name: Build LEDE (coolsnowwolf/lede)

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'LEDE 源码仓库地址'
        required: true
        default: 'https://github.com/coolsnowwolf/lede'
      repo_branch:
        description: '源码分支'
        required: true
        default: 'master'
      config_path:
        description: '你仓库内的 .config 路径（如 configs/x86_64.config）; 留空则要求 lede 目录已有 .config'
        required: false
        default: ''
      feeds_conf_path:
        description: '你仓库内的 feeds.conf.default 路径（可选）'
        required: false
        default: ''
      files_dir:
        description: '你仓库内的 files 目录（可选，用于覆盖固件）'
        required: false
        default: ''
      use_ccache:
        description: '启用 ccache'
        type: boolean
        required: true
        default: true
      make_jobs:
        description: 'make 并行线程数（留空=自动 nproc）'
        required: false
        default: ''
      enable_ssh:
        description: '启用 SSH 调试（tmate）'
        type: boolean
        required: true
        default: false
      do_release:
        description: '编译完成后创建 Release 并上传产物'
        type: boolean
        required: true
        default: false

permissions:
  contents: write

concurrency:
  group: lede-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Singapore
      REPO_URL: ${{ inputs.repo_url }}
      REPO_BRANCH: ${{ inputs.repo_branch }}
      CONFIG_PATH: ${{ inputs.config_path }}
      FEEDS_CONF_PATH: ${{ inputs.feeds_conf_path }}
      FILES_DIR: ${{ inputs.files_dir }}
      USE_CCACHE: ${{ inputs.use_ccache }}
      MAKE_JOBS: ${{ inputs.make_jobs }}
      ENABLE_SSH: ${{ inputs.enable_ssh }}
      DO_RELEASE: ${{ inputs.do_release }}

    steps:
      - name: Checkout (your helper repo)
        uses: actions/checkout@v4

      - name: Show runner disk usage (before cleanup)
        run: |
          df -h
          sudo lsblk

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /opt/hostedtoolcache/Java /opt/hostedtoolcache/Python/3.8* /opt/hostedtoolcache/Python/3.9* || true
          sudo apt-get clean
          sudo docker image prune -af || true
          df -h

      - name: Setup swap (8G) to reduce OOM
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          swapon -s
          free -h

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ack antlr3 asciidoc autoconf automake autopoint binutils bison \
            build-essential bzip2 ccache cmake cpio curl device-tree-compiler \
            fastjar flex gawk gettext git gperf haveged help2man intltool jq \
            libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev \
            libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
            libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip-full \
            patch pkg-config python3 python3-distutils python3-pip qemu-utils rsync \
            scons subversion swig texinfo uglifyjs unzip upx-ucl wget \
            xz-utils zlib1g-dev

      - name: Prepare ccache
        if: env.USE_CCACHE == 'true'
        run: |
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "USE_CCACHE=1" >> $GITHUB_ENV
          ccache -M 5G || true
          ccache -s || true

      - name: Cache ccache
        if: env.USE_CCACHE == 'true'
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.workflow }}-

      - name: Clone LEDE
        run: |
          git clone --depth 1 -b "${REPO_BRANCH}" "${REPO_URL}" lede
          cd lede && git log -1 --oneline

      - name: Inject custom feeds.conf.default (optional)
        if: env.FEEDS_CONF_PATH != ''
        run: |
          test -f "${FEEDS_CONF_PATH}" || { echo "Feeds not found: ${FEEDS_CONF_PATH}"; exit 1; }
          cp -f "${FEEDS_CONF_PATH}" lede/feeds.conf.default

      - name: Update & install feeds
        working-directory: lede
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Inject files/ overlay (optional)
        if: env.FILES_DIR != ''
        run: |
          test -d "${FILES_DIR}" || { echo "Files overlay not found: ${FILES_DIR}"; exit 1; }
          mkdir -p lede/files
          rsync -aH --delete "${FILES_DIR}/" lede/files/

      - name: Prepare .config
        run: |
          set -e
          cd lede
          if [ -n "${CONFIG_PATH}" ]; then
            cp -f "${GITHUB_WORKSPACE}/${CONFIG_PATH}" .config
          fi
          if [ ! -f .config ]; then
            echo "::error::缺少 .config。请在 inputs.config_path 指向你的配置，或把 .config 预先放到 lede/ 目录。"
            exit 1
          fi
          make defconfig
          head -n 50 .config || true

      - name: Cache dl (source tarballs)
        uses: actions/cache@v4
        with:
          path: lede/dl
          key: dl-${{ runner.os }}-${{ hashFiles('**/.config') }}
          restore-keys: |
            dl-${{ runner.os }}-

      - name: Download sources
        working-directory: lede
        run: |
          MAKEJ="${MAKE_JOBS}"; [ -z "$MAKEJ" ] && MAKEJ=$(nproc)
          make download -j"$MAKEJ" V=s

      - name: Optional SSH (tmate) for debugging
        if: env.ENABLE_SSH == 'true'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        timeout-minutes: 60

      - name: Build firmware
        working-directory: lede
        run: |
          MAKEJ="${MAKE_JOBS}"; [ -z "$MAKEJ" ] && MAKEJ=$(nproc)
          (make -j"$MAKEJ" V=s) || (echo "并行失败，降级 -j1 重试"; make -j1 V=s)
          du -h --max-depth=2 bin/targets || true

      - name: Upload artifacts (bin/targets)
        uses: actions/upload-artifact@v4
        with:
          name: lede-targets-${{ github.run_id }}
          path: lede/bin/targets/**/*
          if-no-files-found: warn
          compression-level: 6
          retention-days: 7

      - name: Upload artifacts (bin/packages)
        uses: actions/upload-artifact@v4
        with:
          name: lede-packages-${{ github.run_id }}
          path: lede/bin/packages/**/*
          if-no-files-found: warn
          compression-level: 6
          retention-days: 7

      - name: Create Release
        if: env.DO_RELEASE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: lede-${{ github.run_id }}-${{ github.sha }}
          name: LEDE Build ${{ github.run_number }}
          body: |
            - Repo: ${{ env.REPO_URL }} @ ${{ env.REPO_BRANCH }}
            - Config: ${{ env.CONFIG_PATH || '.config in lede/' }}
            - Triggered by: ${{ github.actor }}
          draft: false
          prerelease: false
          files: |
            lede/bin/targets/**/*
